### ISSUE TITLE
I think you should provide some Chinese Translation

### ISSUE THREAD

**Issue by Maybe0019** [BootleggersROM/packages_apps_Settings#1]
Such as:
root manager→root权限管理 ro 超级权限
bootleg dumpster→bootleg配置 or 个性设置
Or you can also open a channel for us to provide translation and put links to the ROM“about bootlegers”

**Comment by eldainosor** [comment]
Hey man, we're glad that you want to help us with translations and we surely want to invite you to [join our crowdin](https://crwd.in/bootleggers-rom) to add your translations. According to google translate your suggested translations are kind of generic (it translates 个性设置 into Personality settings, maybe it's customization but not really well translated, and it sounds pretty generic, so we want our translations to be according to the original text) but well, any questions or doubts, you can join our [telegram group](t.me/keepthebootleg) and we can discuss about it
